package MiscClasses;

public enum EffectType {
	STRENGTH, WEAKNESS, REGENERATION, POISION, PRECISION, DIZZYNESS, FORTUNE, MISFORTUNE, INSTANT_HEALTH, INSTANT_DAMAGE;
	// TODO: add more effects when needed
}
